### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Danielwbolson/LOD_Instancing#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank-you.

**Comment by Danielwbolson** [comment]
There is no license associated with this repository. You may fork this repository, but may not pass the original contents off as your own.


From Github's TOS:
Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.
